### ISSUE TITLE
Change copy for empty lists

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-todos#10]
The text that says "You have no todos" could say something like "Click Add Item above to add a task."

I've changed it to read:
Title: No tasks here
Subtitle: Add new tasks using the field above

Note: We'd like to keep the copy web/mobile agnostic. Since there's no tapping on web and vice versa, we direct them to the field which now says "Type to add new tasks" (per another issue).

Let me know if this addresses your original concern @stubailo.

![screenshot 2014-09-17 16 24 37](https://cloud.githubusercontent.com/assets/263385/4313014/d7c0bbd4-3ec1-11e4-9c9f-3f60fe6a9c4f.png)

**Comment by stubailo** [comment]
Looks good!
