### ISSUE TITLE
Add tooltips to all icons via the title attribute

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-todos#12]

**Comment by domyen** [comment]
System tooltips appear as the little yellow labels (osx) when hovering over an icon for a moment. Tooltips have been added to all icons that aren't accompanied by text. 

I think the original concern was more explanation around the lock icon. The tooltips are the first level of clarification, the second level occurs upon interaction with the icon where we show a JS alert that explains the feature https://github.com/percolatestudio/mdg-todos/issues/14. 

lmk

**Comment by zol** [comment]
Lgtm.
