### ISSUE TITLE
Code changes requested by MDG

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-todos#16]
From Sashko:
- [x] Let's not use the data-\* attributes to select elements with JS. Some experiments on the internet say that attribute selectors can be much slower than class selectors, and also this is a new pattern that many users might not understand. One way of separating classes for styling and for JS could be to prefix the class name with 'js-'.
- [x] We should use the variable name "event" instead of "e" in template event handlers.
  In collections.js, let's use integer names instead of strings to avoid charcode shenanigans and overflowing past Z.
- [x] In router.js, let's comment what the different parts mean (for example, we have a global waitOn because these things are supposed to be present on all pages). Same for the router.onBeforeAction calls.
- [x] In bootstrap.js, please remove the tag data (I think this was a feature that was removed) and use _.each to iterate over the arrays instead of for loops.

In `todos-item.js`, we should:
- [x] Add a comment about the _.throttle in the keyup event and what it does.
- [x] Do event.target.value instead of $(e.target).val(), and same with the blur in the keydown event.
- [x] Instead of _.include([27, 13], e.which), we should use e.which === 27 || e.which === 13 to make it a little simpler.

**Comment by zol** [comment]
@tmeasday over to you. I had some questions around the router. Feel free to make any corrections and close this off when satisfied.

**Comment by tmeasday** [comment]
LGTM.
