### ISSUE TITLE
When you log in or out, there is animation flickering in iOS

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#19]
The animation to open/close the sidebar when the user logs in or out isn't smooth.

**Comment by tmeasday** [comment]
Yeah, this is ugly. It actually happens in desktop Chrome as well at phone resolution (although it's much harder to spot).

Going to add some page to page transitions (fade out/in) now, it might have the side effect of fixing this.

**Comment by tmeasday** [comment]
The reason for this was we didn't redirect until we were done logging out, usually mid way through the menu closing.

Changed the redirect to be instant.

**Comment by zol** [comment]
Lgtm.
