### ISSUE TITLE
Lists should not be visible to an unauthenticated user

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-todos#2]
Lists are visible to unauthenticated users when you're signed in.

Repro
1. Join + Sign in one browser window (that's not the current browser, use an incognito window or different browser)
2. Navigate to localhost:3000 in a second browser
3. Add a new list in the browser that is authenticated
4. You should see the list reflected in the unauthenticated browser window (however locked classes do not get shown)
5. Expected behavior is to have a unique state for authenticated users that is private

**Comment by tmeasday** [comment]
I'm confused. What's the issue? Are private lists being shown to other
users?

**Comment by domyen** [comment]
The issue here is that the public todo lists of logged in users are shown in the menu. This doesn't seem like it would be the expected use case when using an app which you've authenticated. 

The expected behavior is when you login, your lists are associated only with your account and are not visible to anyone else that happens to have the menu open. They can be shared only via a unique URL but are not visible otherwise.

**Comment by tmeasday** [comment]
Note: 

We discussed this. The conclusion is that we should build for the "example app used by a few people" use case rather than the "real app used by thousands". 

So there's not so much of an issue with sharing public lists between users' menus. 

@dominicnguyen close if you are happy with the explanation.
