### ISSUE TITLE
The sidebar should open by swiping on mobile

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#24]
Depending on how hard it is to implement (whether it would introduce a lot of code complexity), it would be good to be able to open the sidebar on mobile by swiping from the left.

**Comment by domyen** [comment]
IIRC it's a bit complex. To get the menu-swipe working like our favorite iOS apps, we need to track the position of the finger and adjust the content area position accordingly. @tmeasday would know best.

**Comment by tmeasday** [comment]
Yeah, our code to do it for Verso is around 100 lines of JS and I think a bit of supporting CSS. Not the easiest code to understand and probably a bit fiddly for the average user to try and replicate, and probably pretty brittle to layout changes.

**Comment by stubailo** [comment]
I see. OK we can put this off till much later then, or never.

**Comment by stubailo** [comment]
Could we do something with just gestures using http://hammerjs.github.io/?

**Comment by tmeasday** [comment]
Yeah, that'd probably be better than nothing and much simpler. Thoughts @dominicnguyen ? -- it would mean it would just be a swiping gesture to open close -- there'd be no nice "grabbing" the edge and moving it.

**Comment by tmeasday** [comment]
Ok, @stubailo - take a look. It works:
- sorta on desktop, but pretty undiscoverable
- _OK_ on cordova
- Kinda janky on Mobile Safari because it interacts with the back/forward gesture which AFAIK cannot be disabled from a webapp.

I'd suggest we only enable it in `Meteor.isCordova`. Any other thoughts?

**Comment by stubailo** [comment]
Looks good to me in cordova, let's enable it only for that case.

**Comment by zol** [comment]
Looks great.
