### ISSUE TITLE
The number next to the task list name should count uncompleted tasks and should appear in the sidebar

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#25]
The number should indicate how many tasks haven't been checked off yet.

**Comment by tmeasday** [comment]
@dominicnguyen needs styling in the menu.

@stubailo you may want to review 76bcf35 -- there's no established pattern for doing these kind of client side joins. You may have better ideas.

**Comment by stubailo** [comment]
What about saving it inside the todo list document and changing it using http://docs.mongodb.org/manual/reference/operator/update/inc/? I don't think we should use publish counts if possible.

**Comment by tmeasday** [comment]
Ok, and just doing the `$inc` client side? I can get behind that.

**Comment by stubailo** [comment]
Yeah, it might not be super atomic, but that might be OK for the example.

**Comment by tmeasday** [comment]
Ok, please review again @stubailo

**Comment by stubailo** [comment]
Looks good!

**Comment by tmeasday** [comment]
Thanks! (cool packages btw, nice talk)

**Comment by stubailo** [comment]
Thanks - I'm really excited about having a page with all of mine on atmosphere!

**Comment by tmeasday** [comment]
I would be too if I wasn't maintainer of like every single package on there ... need to something about that :)

**Comment by tmeasday** [comment]
LGTM.
