### ISSUE TITLE
Initial load should show the todo splash in the loading template

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-todos#28]
The initial load shows a menu (perhaps the loading template on top of that) followed by the list. 
It should show the loading template followed by the list.

**Comment by stubailo** [comment]
Related: the app should do something nice if you start it when you don't have any internet access. This might just mean having the loading screen up forever with the connection warning at the bottom.

**Comment by tmeasday** [comment]
Seems to work well except for one issue: the image tag for the loading page doesn't work.

What is the correct path that we should be specifying? It seems to look for the image on the internal on-device server, fail to find it, and not forward it through to the real server. What should it be doing? @stubailo

**Comment by stubailo** [comment]
interesting. I'll ask around to see if this is a bug.

**Comment by zol** [comment]
@stubailo any ideas on this one?

**Comment by stubailo** [comment]
Fixed by 0.9.4-pre.8
