### ISSUE TITLE
Scrolling is weird on iPhone

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#29]
If you run the app on an iPhone or iOS simulator, and you click and drag the title bar/list name, then let go and try to scroll the task list, for some reason it tries to scroll the whole page and it's impossible to scroll the list itself unless you tap inside a list item first.

Let me know if this is too vague of a description.

**Comment by domyen** [comment]
@zol @tmeasday So this is an issue that we encountered on previous mobile-web apps: when a user tries to scroll a fixed nav element they end up scrolling the entire page (which is impossible because we set overflow hidden) instead of the real scrollable area. 

Any further thinking on this one?

**Comment by tmeasday** [comment]
Ahh, the dreaded rubber band scrolling. I can't actually remember the conclusion for Verso, which seems to not have this problem (also doesn't have a title bar). @zol I'm guessing you have a better memory on this stuff than me?

**Comment by zol** [comment]
Fixed via `config.xml`

**Comment by tmeasday** [comment]
Looks good to me. Although now the app launches in landscape for me. Do you see this @zol ?

**Comment by tmeasday** [comment]
Fixed I guess. @zol tell me if that was wrong.

**Comment by zol** [comment]
@tmeasday Ah shit sorry, I fixed that then got distracted and didn't check it in. Boo :(
