### ISSUE TITLE
Splash and tile assets for cordova

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-todos#33]

**Comment by zol** [comment]
@dominicnguyen I've added the default assets in https://github.com/percolatestudio/mdg-todos/commit/118d82f46cb2ade661fe827cd8fb8d07caeee653 . Please override them in the project with our assets in the correct dimensions

**Comment by domyen** [comment]
Try them out. https://github.com/percolatestudio/mdg-todos/commit/dd53953b5dcb89f6143d7ede83b354c032234c53
