### ISSUE TITLE
Sometimes when a list is opened, the "no todos" screen shows up for a split second before all of the todos stream in

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#35]
We should add some code to show a loading indicator while all of the todos for a list are loading, and then show them all at once.

**Comment by stubailo** [comment]
Especially prominent on a mobile device possibly due to slow connection or DOM rendering

**Comment by tmeasday** [comment]
Over to you @dominicnguyen. To see the state on desktop, add

```
  Meteor._sleepForMs(4000);
```

to the `'todos'` publication in publish.js

**Comment by domyen** [comment]
I'm good with the styling and message.

**Comment by zol** [comment]
Looks great!
