### ISSUE TITLE
When you tap the list title on iOS, sometimes the keyboard doesn't open to allow you to edit it

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#36]
Sometimes you have to tap twice.

**Comment by tmeasday** [comment]
Any ideas about a reproduction on this one? I wasn't able to reproduce it in the simulator (and I'm having trouble running on device right now)

**Comment by domyen** [comment]
@stubailo would this have something to do with the ios status bar covering part of the input?

Similar to the issue we encountered with the icons:
https://github.com/percolatestudio/mdg-todos/issues/18
