### ISSUE TITLE
iOS list edit not focussing input when select option is clicked

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-todos#4]
iOS is not focussing the list name input when clicking on the edit option in the select. The behavior should be identical to web in that the 'Edit' option immediately focusses the input field.

**Comment by tmeasday** [comment]
Hmm. This appears to be impossible in mobile safari. @zol I believe you are the resident expert in this area.

**Comment by zol** [comment]
Yeah, not possible. In iOS you can only focus an input and bring up the keyboard from a `click` event handler. @dominicnguyen we either need to design around this or live with it.

**Comment by domyen** [comment]
Let's live with it. The other alternative is to create custom dropdown menus which isn't great with mobile.
