### ISSUE TITLE
Sidebar background doesn't show up in Android app

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#40]
Might be some sort of bug with CSS and the crappy default android webview.

**Comment by stubailo** [comment]
Fixed with solid color fallback. apparently the -webkit prefix doesn't really help.

**Comment by domyen** [comment]
Coverage of the Android before it used Chrome as the default browser is notoriously spotty. I'm happy with the solid color solution but we can investigate linear-gradients in Android webview further if necessary.

**Comment by stubailo** [comment]
OK I think the solid color fallback is totally fine, since you can't see the gradient as much on a small mobile screen anyway.
