### ISSUE TITLE
When the app initially loads, if the DDP connection takes too long the "connection problem" message shows up for a second.

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#41]

**Comment by zol** [comment]
@stubailo - Can you recommend a non-hacky way to solve this? We're conscious of keeping the example code clean.

**Comment by stubailo** [comment]
Yeah you're right, using Meteor.status() is probably the best way to do this right now.

**Comment by dburles** [comment]
I just set a flag after initial load and then only show the notification if the flag is true

**Comment by stubailo** [comment]
I did the flag setting solution, it wasn't that bad. The problem was especially noticeable on Android

**Comment by zol** [comment]
Does that imply that if you're say offline when you load the app and really
are attempting to connect you won't be notified?​

**Comment by dburles** [comment]
This is basically how I did it for atmos. Thoughts?

``` js
var hasBeenConnected = false;
Tracker.autorun(function() {
  if (! Meteor.status().connected && hasBeenConnected) {
    Session.set('offline', true);
  } else {
    hasBeenConnected = true;
    Session.set('offline', false);
  }
});
```

**Comment by dburles** [comment]
Hmm I see what you're saying @zol

**Comment by stubailo** [comment]
I've pushed my code already, you can see what I did

**Comment by stubailo** [comment]
"Does that imply that if you're say offline when you load the app and really
are attempting to connect you won't be notified?​" It will notify you in 1 second. I think the most common case is where it takes <1 second to connect and you see the notification flash for a tiny bit.

We can also tune the timeout.

**Comment by dburles** [comment]
I guess the 1 second timeout seems kind of arbitrary, something more concrete would be nicer, but I can't really think of anything better

**Comment by stubailo** [comment]
It is completely arbitrary. Maybe something like 2-3 seconds would be better.

I think the point is the warning should pop up before the user really starts wondering "why is my data not showing up"

**Comment by dburles** [comment]
ya. I guess it's reasonable enough
