### ISSUE TITLE
Swiping to open sidebar doesn't work on android

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#42]

**Comment by tmeasday** [comment]
It does work (at least on my device), it's just very unreliable.

There are a bunch of tickets against the older hammer.js1.1 that have a variety of arcane fixes:  e.g. https://github.com/hammerjs/hammer.js/issues/366. 

It's unclear if any of them will work in 2.0. I'm not sure how much messing around we want to do with this?

**Comment by stubailo** [comment]
If there isn't a concise solution it's probably not worth it.

**Comment by stubailo** [comment]
Fixed this by upgrading to hammer 2

**Comment by tmeasday** [comment]
Was I really using hammer 1? Oh man :facepalm:. Thanks @stubailo
