### ISSUE TITLE
Fix the email wrapping

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#45]
We need to change the UI somehow so that email addresses are not wrapped, or are wrapped more intelligently. Even very short email addresses are wrapped, such as "sashko@meteor.com".

**Comment by zol** [comment]
Waiting on Dom to get back and make a call. The other option is ellipsizing the emails.

**Comment by domyen** [comment]
Let's remove the '@domain.com' from the text we show in the UI to give us an allowance for lengthier  usernames.

**Comment by stubailo** [comment]
Yeah, that sounds like a good option!
