### ISSUE TITLE
Make private/public in mobile

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-todos#6]
1. In mobile width, perhaps we should set the label in the select to be 'Make private/Make public' to make it clearer to the user that's going to be the result of their action.
2. It would be nice in mobile to also show the private/public status of a list as you have no visual feedback that anything has happened after you change the state via the ui.

@dominicnguyen what do you think?

**Comment by domyen** [comment]
1. Agree and done.
2. I'd rather leverage our notification UI to validate user actions. The information in the header will be quite dense if we try to symbolize and message the privacy state. Do we have a notification api setup to do this? (i.e., similar to the connection dialog)

**Comment by zol** [comment]
We don't have our full blown notifications area on this project and I think
it would probably blow out the scope to include it.

_Zoltan Olah_
Partner/Engineer
http://percolatestudio.com
+1 415 696 4455

**Comment by zol** [comment]
Not a problem.
