### ISSUE TITLE
Routing error if logging out with no public list

### ISSUE THREAD

**Issue by tmeasday** [percolatestudio/mdg-todos#7]
As we are trying to redirect to a null list. @zol should we reuse the code in the new list event handler somehow?

**Comment by zol** [comment]
I don't think so. Having no lists is a valid state I thought - refresh http://localhost:3000 after deleting all your lists.

**Comment by zol** [comment]
Actually, this 'empty' state seems totally broken on mobile too.

**Comment by domyen** [comment]
We should always have at least one list.

**Comment by tmeasday** [comment]
@dominicnguyen so does this mean we should create a new list if you delete you final list?

**Comment by domyen** [comment]
We should prevent users from deleting the last list. If they're on the last list and try to delete it, let's pop up a JS alert that says 'You must have one todo list'.

**Comment by tmeasday** [comment]
Hmmm. I implemented this but it doesn't handle all the edge cases.
1. What if a different user makes your last list private?
2. What if a different user deletes the last public list (but themselves have a private list)?

Perhaps the rule should be "there should always be at least one public list"?

**Comment by domyen** [comment]
@tmeasday makes sense, let's do that.

**Comment by tmeasday** [comment]
Ok, done. The rule is enforced client side so a) is insecure and b) highly susceptible to race conditions.

Are you OK with this @stubailo ? (we are still using `insecure` in this app of course). Should I add an explanatory comment?

**Comment by domyen** [comment]
lgtm
